### ISSUE TITLE
Flux-infused Jetplate?

### ISSUE THREAD

**Issue by HanPrower** [TehNut-Mods/RedstoneArmory#10]
I may have somehow missed it. I do see in the config SimplyJetpacks integration, but I'm not sure what that does, if anything.

It would be very nice to have an enederium upgrade to the JetPlate though.

**Comment by TehNut** [comment]
It's... Coming...

Trying to figure out how to do it correctly. I've never seen his registration method before.

**Comment by TehNut** [comment]
As of https://github.com/TehNut/RedstoneArmory/commit/a7a03350378755726ffadad1b62ca663bd077624 I've decided to drop this idea for now. I'd prefer to get around to finishing _actual_ features at some point.

**Comment by HanPrower** [comment]
Oh, that sucks.

Pretty sure a new Jetplate is a new feature though. Hopefully what you add in interim is awesome then ;)

**Comment by TehNut** [comment]
It was more of a "hey this would be cool to add". Then realized that he does some stuff I've never seen for item creation.
