### ISSUE TITLE
Crash with Gelid Enderium Axe

### ISSUE THREAD

**Issue by asdaa0** [TehNut-Mods/RedstoneArmory#15]
When i try to right click a gelid enderium axe it in the air my client crashes.

Crash Report: http://pastebin.com/1yWEHaJ2
Modpack: TPPI2

**Comment by SenojLuap** [comment]
Got the same crash but on starting MC. I'm using a custom modpack
Crash: http://pastebin.com/GVgurYbn

**Comment by TehNut** [comment]
Fixededed. I'm an idot.

Also:
Those aren't anywhere near the same crash.

**Comment by BBoldt** [comment]
ya damn idot
