### ISSUE TITLE
Crash: New Version Requires Baubles

### ISSUE THREAD

**Issue by K4N0** [TehNut-Mods/RedstoneArmory#16]
.

**Comment by TehNut** [comment]
It has a soft dependency and should tell you that at startup. Can you post your log?

**Comment by Badcholo** [comment]
It didn't say anything at startup. It just crashed on me. 
http://pastebin.com/xEinZWzb

**Comment by TehNut** [comment]
Should be fixed in the latest build.

**Comment by Badcholo** [comment]
Fixed, doesn't crash when baulbles isn't installed. Would be nice to tell players that it's an option to use baubles.
