### ISSUE TITLE
Feature Request: Paxel or MultiTool

### ISSUE THREAD

**Issue by K4N0** [TehNut-Mods/RedstoneArmory#17]
.

**Comment by SgtPunishment** [comment]
Multi-tools I believe are very cheaty, and I don't honestly think the authors would add anything like that, but I could be wrong.

**Comment by Badcholo** [comment]
Multi-tools aren't cheaty. it just saves you hotbar slots and having to keep swapping hotbar items. The crafting can stay the same, just a way to combine them all. It's kind of dumb that with all this technology we can't craft a multi tool.

**Comment by Tombenpotter** [comment]
Naah.
