### ISSUE TITLE
Swimming in lava

### ISSUE THREAD

**Issue by K4N0** [TehNut-Mods/RedstoneArmory#19]
.

**Comment by Badcholo** [comment]
I'll just remove myself from here.

**Comment by TehNut** [comment]
This one I'll fix since you can swim in lava.

Edit: Just on mine, not on Redstone Arsenals.

**Comment by Badcholo** [comment]
Awsome, your so nice,

**Comment by TehNut** [comment]
Apparently I fixed this in a past commit.
