### ISSUE TITLE
Gelid Rod No Texture

### ISSUE THREAD

**Issue by xCouzchat7** [TehNut-Mods/RedstoneArmory#2]
I don't know what the problem may be. I made sure to check for ID conflicts.

![gelid](https://cloud.githubusercontent.com/assets/6355481/3332215/aba5cb1c-f7e4-11e3-92f2-de3923be7951.png)

**Comment by TehNut** [comment]
Looking into this right now. I also noticed another issue where I reversed config options, thus disabling abilities when they should be enabled...

**Comment by TehNut** [comment]
Fixed in https://github.com/TehNut/RedstoneArmory/commit/4df65c2cbd5b8c61bdc6d714035fe8c700ec4006
