### ISSUE TITLE
strange Sword issue, need more author info

### ISSUE THREAD

**Issue by HanatakeYurii** [TehNut-Mods/RedstoneArmory#23]
Hi,

I'm playing a lot with your mods for a long time.
Now it came a strange issue with the Gelid Enderium Sword. 

First, what I don't know if it's a bug but at http://ftbwiki.org/Gelid_Enderium_Sword it is said:
"The sword has an internal energy storage of 320000RF and uses 350RF per action. It will do +15 attack damage normally and +23 when empowered; a diamond sword is +7 for comparison. "

I never got 23. Should it be or not?
IMHO I think 23 would be a great value.

Second whatever the sword is empowered or not it deals the same 16 damages, but it says 15 when off and 15 +1 when empowered. Tested multiple times against Iron Golems.

In some way there is a problem.

PS: Maybe I should suggest a next high level (that could be optional) that make eve more damages, since there are many-used mods like Thaumcraft and Draconic Evolution that adds Swords that deals more than +40 damages.

Tested with RArm 1.2.0-32 & ttCore 0.1.1.76

**Comment by TehNut** [comment]
This was an issue with Redstone Arsenal a long time ago so I dropped my bonus to make it not misleading. I never really looked back at it to fix it. I'll put it on my to-do list.

It _is_ supposed to do the +23 when empowered like the Wiki says.

**Comment by HanatakeYurii** [comment]
thanks :)

**Comment by HanatakeYurii** [comment]
Any hope for a build in next days?

PS: Tonius (Simply Jetpacks) agreed to add a graphical update of his jetplate to match Redstone Armory design as I submitted him as request. So from the current new version it provides a bit of support for your mod :)

**Comment by TehNut** [comment]
> Any hope for a build in next days?

I'm currently swapping out the "useless and shitty" pickaxe ability with a "not useless or shitty" ability.

I'm also supposed to be getting a new texture for the Enderium Armor from @BBoldt since mine is terribad.

> Tonius (Simply Jetpacks) agreed to add a graphical update of his jetplate to match Redstone Armory design as I submitted him as request

I heard. Tis why I'm forcing BBoldt to make that texture ;)

**Comment by BBoldt** [comment]
_shows off whip marks_

**Comment by HanatakeYurii** [comment]
XD you maked laugh to death with your textures things.
I'm glad to see you didn't forget Redstone Armory.
I'll wait until your next update.

Good luck with the whip... I mean with BBoldt

PS: what are you talking about "useless and shitty" pickaxe ability? The ability to teleport blocks behind? If so I wouldn't say shitty, but somewhat strange (and I don't count times I got stuck in rock with this)

**Comment by TehNut** [comment]
> PS: what are you talking about "useless and shitty" pickaxe ability? The ability to teleport blocks behind? If so I wouldn't say shitty, but somewhat strange (and I don't count times I got stuck in rock with this)

It gets called useless more often than people thing "oh neat". We mainly decided to do that as it was different from what everybody and their mother has done. New ability will allow you to link your pick to any IInventory. All drops from mined blocks (when empowered) will be sent to that inventory. If it's valid for the slot, of course.

**Comment by rdelro** [comment]
The pick could definitely use a better or rather improved ability..

**Comment by HanatakeYurii** [comment]
Oooh, I see, great idea, will be very useful, so more than previous behavior.
But so, will the pickaxe keep it's normal ability to pick lock in "columns"?
And for the new ability, I suppose it will be the "empowered" behavior, not the normal one, isn't it?

**Comment by TehNut** [comment]
@rdelro @HanatakeYurii 

http://tehnut.info/share/s9MEd5GVC.mp4

Just finished preliminary code thanks to some help from the Blood Magic repo.

**Comment by HanatakeYurii** [comment]
Oooh great.
So it will be 1 block at time.

PS: Note to myself, stop putting "Oooh" at every message.

**Comment by TehNut** [comment]
No, I didn't show that it does the 1x3x1 thing

**Comment by rdelro** [comment]
That ability already looks a lot better! I just didn't like getting stuck in blocks with its uh, previous ability? Still can't wait to see this evolve! Great stuff.

**Comment by HanatakeYurii** [comment]
Thx. Good to see 1x3x1 back :)
Keep up the good work
I'll keep an eye on your works

**Comment by BBoldt** [comment]
@HanatakeYurii 
![](http://i.imgur.com/oQXwHwF.png)
![](http://i.imgur.com/MaJu4Q4.png)

**Comment by TehNut** [comment]
Derailing aside, this has been fixed in 5f386ce84bc11815d1e37d3566ce8b9df893a335. Apparently I pushed that commit and forgot to close this.

**Comment by HanatakeYurii** [comment]
Yay, thanks
