### ISSUE TITLE
Incompatibility with latest EnderIO/EnderCore...

### ISSUE THREAD

**Issue by ate0ate** [TehNut-Mods/RedstoneArmory#24]
The latest builds of enderIO and enderCore have broken compatibility with ttCore. A message appears a startup stating to remove ttCore and use only enderCore, but doing that leads to a different startup message stating that Redstone Armory needs ttCore. Sigh.

**Comment by TehNut** [comment]
Will fix and push an update later today.

**Comment by TehNut** [comment]
961a2e3198ae281a815c9e60bdefa14f702ffdf3

**Comment by ate0ate** [comment]
Thank you good sir, you are awesome.
