### ISSUE TITLE
[Feature] Crook and Hammer

### ISSUE THREAD

**Issue by gabor7d2** [TehNut-Mods/RedstoneArmory#27]
It would be nice to have an Enderium version of the Flux-Infused Crook and Hammer added by Ex Astris / Ex Astris Rebirth. 
The **Enderium Flux Hammer** Could like hammer a 3x3 area.
The **Enderium Flux Crook** Could do like the same thing as the sickle does, just it gives silkworm.

This is really not a big idea, but it's something. I hope you like it. :smile:

**Comment by TehNut** [comment]
Sure why not. What could go wrong?

**Comment by Tombenpotter** [comment]
Now you're guaranteed it will go wrong.

**Comment by rdelro** [comment]
I can hear the fans screaming "Too OP, nerf it! nerf it!" oh boy =_=

**Comment by TehNut** [comment]
Project dropped
