### ISSUE TITLE
Suggestion: More Configurability

### ISSUE THREAD

**Issue by RoloEdits** [TehNut-Mods/RedstoneArmory#28]
It would be awesome if there were more configurability in the configs to change things like damage absorption levels, rf per hit, max rf stored, enchantability, protection levels, attack damage ,ect.
so one could balance it within there mod pack.

**Comment by TehNut** [comment]
I'll rework the entire config to look more like the RedstoneArsenal one.

**Comment by RoloEdits** [comment]
Thank You very much. It means a lot that you take in peoples suggestions of whom you have never met.

**Comment by TehNut** [comment]
I just didn't realize how open their config was. If I had known, it would have looked like that long ago.

**Comment by RoloEdits** [comment]
Are you only going to add only what they have? Or can you also add some of the things I requested because although there configs are quite customizable they don't let you change some of the things that I have listed.

**Comment by TehNut** [comment]
Project dropped
