### ISSUE TITLE
[Bug] Ingame Config gui button causes crash

### ISSUE THREAD

**Issue by SnowShock35** [TehNut-Mods/RedstoneArmory#31]
Hi,
I've found a crash with Redstone Armory, details are provided below;
- Minecraft 1.7.10
- Forge 10.13.4.1448
- Redstone Armory 1.2.0-41
- Redstone Arsenal 1.1.1-89
- FastCraft Enabled

Crash Report: http://pastebin.com/RQixQMXf

**Comment by TehNut** [comment]
Project dropped
