### ISSUE TITLE
Tuberous Armor Crash (failed to handle packet)

### ISSUE THREAD

**Issue by Oninaig** [TehNut-Mods/RedstoneArmory#4]
User gets disconnected immediately if they connect while they are wearing the tuberous armor. Latest version of Redstone Armory.

Heres the server output: http://pastebin.com/EjwT8Qab

**Comment by TehNut** [comment]
Yes, known. It's because of how I coded the temporary "auto-feeder" mechanic. I meant to get around to fixing it already but I've been busy lately. Use an NBT Editor to remove the armor from your player in the meantime.

I shall fix soon™

Edit: Going to leave open until fixed.

**Comment by TehNut** [comment]
Fixed in 300248a43a4bb063913101dc4b8ffd42ed1f2ba9
