### ISSUE TITLE
Sword magnetism with other items

### ISSUE THREAD

**Issue by FakoTheGreat** [TehNut-Mods/RedstoneArmory#6]
As long as the sword is empowered in the inventory, the magnetism effect activates no matter what item you are holding when you hold down the right mouse button.  While this can be useful with things such as Botania's Horn of the Wild, it is a pain when trying to scan things with a thaumometer...

Running 1.7.10 version 1.1-6

**Comment by TehNut** [comment]
Fixed in e21ed3ee12005835ccacf90f45a0687964c90312
